name: Build Release
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22'
      - run: npm install
      - run: npm run build
      - name: Zip extension
        run: |
          cd dist
          zip -r ../only-video.zip .
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: only-video.zip
          token: ${{ secrets.GITHUB_TOKEN }}

